### ISSUE TITLE
Transitions

### ISSUE THREAD

**Issue by loq24** [Wildhoney/ReactDelayed#1]
Is it possible to use transitions like fade in & fade out in between mounting and unmounting components?

**Comment by Wildhoney** [comment]
Nope, sadly not. You'll have to wrap the component again using [`ReactTransitionGroup`](https://github.com/reactjs/react-transition-group).

**Comment by loq24** [comment]
Ok thanks! Nice work btw :)

**Comment by Wildhoney** [comment]
Thanks @loq24 👍
